"""
XRPimeter main application.

This file coordinates the XRPimeter modules.

The individual jobs are handled by separate modules:

    xr18.py
        Finds the XR18 and receives the 18-channel audio stream.

    usb_storage.py
        Finds and checks the USB recording storage.

    meter.py
        Calculates the audio level for each channel.

    recorder.py
        Writes the audio stream to 18 separate WAV files.
        Handles recording sessions and 20-minute part rollover.

    led.py
        Controls the 20 WS2812 status and channel LEDs.

    xrp_log.py
        Records important XRPimeter events in the system log.

    time_status.py
        Determines whether the Raspberry Pi's system clock can be trusted.

main.py coordinates these jobs rather than implementing their internal
behaviour.

The basic operating principle is:

    XR18 connected
        |
        +----> Metering
        |
        +----> USB available?
                  |
                  +---- YES ---> Recording
                  |
                  +---- NO ----> Metering continues

Therefore XRPimeter can operate as a meter without a USB drive.
"""


import signal
import time


# ---------------------------------------------------------------------------
# XRPimeter modules
# ---------------------------------------------------------------------------

from xr18 import XR18

from usb_storage import (
    find_usb,
    recordings_directory,
    usb_is_available,
)

from meter import Meter

from recorder import Recorder

from led import LEDs

from xrp_log import get_logger


# ---------------------------------------------------------------------------
# Display
# ---------------------------------------------------------------------------

from display import Display
display = Display()


# ---------------------------------------------------------------------------
# Create application components
# ---------------------------------------------------------------------------

xr18 = XR18()

meter = Meter()

leds = LEDs()


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

LED_UPDATE_INTERVAL = 1.0 / 90.0

last_led_update = 0.0


# ---------------------------------------------------------------------------
# Application state
# ---------------------------------------------------------------------------

# No USB storage has been found yet.
usb_mount_point = None


# No recorder exists until usable USB storage is found.
recorder = None


# Get the central XRPimeter logger.
logger = get_logger()


# ---------------------------------------------------------------------------
# Shutdown state
# ---------------------------------------------------------------------------

# This prevents the shutdown routine from being executed twice if, for
# example, SIGTERM arrives while the application is already shutting down.
shutdown_requested = False


# ---------------------------------------------------------------------------
# Shutdown handler
# ---------------------------------------------------------------------------

def request_shutdown(signum=None, frame=None):
    """
    Request an orderly XRPimeter shutdown.

    systemd normally sends SIGTERM when the service is stopped or the
    Raspberry Pi begins shutting down.

    We deliberately do not perform the entire shutdown inside the signal
    handler. Instead we set a flag and allow the main loop to perform the
    cleanup safely.
    """

    global shutdown_requested

    if shutdown_requested:
        return


    shutdown_requested = True


# ---------------------------------------------------------------------------
# Register shutdown signals
# ---------------------------------------------------------------------------

# SIGTERM is the important one for systemd.
signal.signal(
    signal.SIGTERM,
    request_shutdown
)


# SIGINT is normally generated by Ctrl+C.
#
# This gives manual testing the same orderly shutdown behaviour.
signal.signal(
    signal.SIGINT,
    request_shutdown
)


# ---------------------------------------------------------------------------
# Application startup
# ---------------------------------------------------------------------------

print(
    "XRPimeter starting..."
)

print()


logger.info(
    "XRPimeter application starting"
)


# ---------------------------------------------------------------------------
# Main application loop
# ---------------------------------------------------------------------------

try:

    while not shutdown_requested:

        # -------------------------------------------------------------------
        # Find XR18
        # -------------------------------------------------------------------

        if not xr18.connected:

            if xr18.connect():

                print(
                    f"XR18 connected: "
                    f"{xr18.device_name}"
                )

                print()


                logger.info(
                    f"XR18 connected: "
                    f"{xr18.device_name}"
                )

            else:

                # XR18 is allowed to be absent during normal operation.
                #
                # Do not fill the OLED diagnostic screen with this.
                # The dashboard will eventually show XR18 status.
                time.sleep(2)

                continue


        # -------------------------------------------------------------------
        # Find USB storage
        # -------------------------------------------------------------------
        #
        # USB recording is optional.
        #
        # If no USB is present, metering continues normally.

        if usb_mount_point is None:

            usb_mount_point = find_usb()


            if usb_mount_point is not None:

                logger.info(
                    f"USB storage ready: "
                    f"{usb_mount_point}"
                )


                # -----------------------------------------------------------
                # Create XRPimeter recording directory
                # -----------------------------------------------------------

                recording_root = recordings_directory(
                    usb_mount_point
                )


                if recording_root is None:

                    logger.error(
                        "Unable to create XRPimeter recording directory"
                    )


                    usb_mount_point = None


                else:

                    # -------------------------------------------------------
                    # Create recorder
                    # -------------------------------------------------------

                    recorder = Recorder(
                        recording_root
                    )


                    # Start a new recording session.
                    if recorder.start():

                        logger.info(
                            "Recorder started"
                        )

                    else:

                        logger.error(
                            "Recorder failed to start"
                        )

                        recorder = None


        # -------------------------------------------------------------------
        # Check existing USB storage
        # -------------------------------------------------------------------
        #
        # If the USB drive disappears during recording, stop the recorder
        # cleanly and return to metering-only operation.
        #
        # This is deliberately NOT shown on the diagnostic OLED screen.
        # The normal dashboard will show USB status.

        if usb_mount_point is not None:

            if not usb_is_available(
                usb_mount_point
            ):

                logger.warning(
                    "USB storage disappeared"
                )


                # Close the current WAV files cleanly.
                if recorder is not None:

                    recorder.stop()

                    recorder = None


                # Forget the old USB mount.
                usb_mount_point = None


                # Update LEDs immediately.
                leds.update(
                    levels=meter.levels,
                    recording=False,
                    usb_available=False,
                )


                # Give Linux a moment to settle.
                time.sleep(1)

                continue


        # -------------------------------------------------------------------
        # Read audio from XR18
        # -------------------------------------------------------------------

        length, data = xr18.read()


        # -------------------------------------------------------------------
        # Handle an empty XR18 read
        # -------------------------------------------------------------------

        if length <= 0 and data == b"":

            continue


        # -------------------------------------------------------------------
        # Handle an actual XR18 failure
        # -------------------------------------------------------------------

        if data is None:

            logger.warning(
                "XR18 audio stream lost"
            )


            # Stop recording cleanly if necessary.
            if recorder is not None:

                recorder.stop()

                recorder = None


            # Release the ALSA device.
            xr18.disconnect()


            # Clear stale LED information immediately.
            leds.xr18_disconnected(
                usb_available=(
                    usb_mount_point is not None
                )
            )


            # On the next loop the XR18 will be discovered again.
            continue


        # -------------------------------------------------------------------
        # Process audio with the meter
        # -------------------------------------------------------------------

        levels = meter.process(
            data
        )


        # -------------------------------------------------------------------
        # Update physical LEDs
        # -------------------------------------------------------------------

        now = time.monotonic()


        if (
            now - last_led_update
            >= LED_UPDATE_INTERVAL
        ):

            leds.update(
                levels=levels,
                recording=(
                    recorder is not None
                    and recorder.recording
                ),
                usb_available=(
                    usb_mount_point is not None
                ),
            )


            last_led_update = now


        # -------------------------------------------------------------------
        # Send audio to recorder
        # -------------------------------------------------------------------

        if recorder is not None:

            recording_ok = recorder.write(
                data
            )


            # If Recorder reports a failure, stop using it.
            if not recording_ok:

                logger.error(
                    "Recorder stopped or failed"
                )

                recorder = None


# ---------------------------------------------------------------------------
# Application shutdown
# ---------------------------------------------------------------------------

finally:

    # -----------------------------------------------------------------------
    # Prevent shutdown from being performed twice.
    # -----------------------------------------------------------------------

    shutdown_requested = True


    # -----------------------------------------------------------------------
    # Shutdown diagnostic
    # -----------------------------------------------------------------------

    print()
    print(
        "XRPimeter stopping..."
    )
    print()


    logger.info(
        "XRPimeter shutdown requested"
    )


    # -----------------------------------------------------------------------
    # Tell OLED that shutdown has started
    # -----------------------------------------------------------------------
    #
    # The exact Display import/constructor needs to match your existing
    # display module.

    display.diagnostic([
       "XRPimeter",
        "SHUTTING DOWN",
        "",
        "Stopping recorder...",
    ])


    # -----------------------------------------------------------------------
    # Stop recorder
    # -----------------------------------------------------------------------

    if recorder is not None:

        logger.info(
            "Closing recording session"
        )


        print(
            "Closing WAV files..."
        )


        # The Recorder owns the WAV files, so Recorder.stop() is responsible
        # for closing them correctly and updating their WAV headers.
        recorder.stop()

        recorder = None


    # -----------------------------------------------------------------------
    # Update shutdown diagnostic
    # -----------------------------------------------------------------------

    display.diagnostic([
        "XRPimeter",
        "SHUTTING DOWN",
        "",
        "WAV files closed",
        "Stopping XR18...",
    ])


    # -----------------------------------------------------------------------
    # Disconnect XR18
    # -----------------------------------------------------------------------

    if xr18.connected:

        xr18.disconnect()


    logger.info(
        "XR18 disconnected"
    )


    # -----------------------------------------------------------------------
    # Shutdown LEDs
    # -----------------------------------------------------------------------

    print(
        "Running shutdown animation..."
    )


    leds.shutdown()


    logger.info(
        "XRPimeter shutdown sequence complete"
    )


    # -----------------------------------------------------------------------
    # Final OLED message
    # -----------------------------------------------------------------------
    #
    # IMPORTANT:
    #
    # This is intentionally the LAST display update.
    #
    # The OLED can remain displaying this message after the XRPimeter
    # process exits and while Linux completes the remainder of its shutdown.
    #
    # It therefore means:
    #
    #     XRPimeter has finished its work.
    #     It is now safe for the system to be powered off.
    #
    # It does NOT mean that Linux has already completely powered down.

    display.diagnostic([
        "XRPimeter",
        "",
        "Shutdown complete",
        "",
        "SAFE TO POWER OFF",
    ])


    print()
    print(
        "XRPimeter stopped."
    )
    print(
        "Safe to power off."
    )
